### ISSUE TITLE
How to install plugins in Ubuntu system?

### ISSUE THREAD

**Issue by be-engineer** [j2969719/doublecmd-plugins#33]
I use ubuntu system，when I install these plugins on doublecmd,always prompt missing .so file，what can I do?

**Comment by j2969719** [comment]
most plugins are dynamically linked and rely on dependencies like libraries or programs that must also be installed on the system. since this shitcode was made for myself, and i myself use archlinux, cant tell the specific names of the packages needed by the specific plugin or their presence on other distros¯\_(ツ)_/¯

afaik compiled plugins for ubuntu can be found [here](https://disk.yandex.ru/d/jhgHgkt1ypuhPw/other)
